services:

  db:
    image: mysql:latest
    container_name: mysql-server
    environment:
      MYSQL_DATABASE: power-bff
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ../power-bff-data/mysql:/var/lib/mysql
    networks:
      - power-network

  backend:
    image: openjdk:21-jdk-slim
    container_name: power-bff
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/power-bff
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db
    volumes:
      - ./power-bff:/app
      - ~/.gradle:/home/gradle/.gradle
    working_dir: /app
    networks:
      - power-network
    command: ./gradlew bootRun 

networks:
  power-network:
